version: '3.8'

services:
  backend-test:
    build:
      context: ./backend
      dockerfile: Dockerfile.test
    environment:
      - NODE_ENV=test
      - DB_HOST=postgres-test
      - DB_PORT=5432
      - DB_NAME=job_automation_test
      - DB_USER=postgres
      - DB_PASSWORD=password
      - REDIS_URL=redis://redis-test:6379
      - JWT_SECRET=test-jwt-secret
    depends_on:
      postgres-test:
        condition: service_healthy
      redis-test:
        condition: service_healthy
    command: npm test
    volumes:
      - ./backend/coverage:/app/coverage

  frontend-test:
    build:
      context: ./frontend
      dockerfile: Dockerfile.test
    environment:
      - VITE_API_URL=http://backend-test:5000/api
    command: npm test
    volumes:
      - ./frontend/coverage:/app/coverage

  postgres-test:
    image: postgres:15
    environment:
      POSTGRES_DB: job_automation_test
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    tmpfs:
      - /var/lib/postgresql/data

  redis-test:
    image: redis:7-alpine
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    tmpfs:
      - /data